### ISSUE TITLE
partially initialized module 'streamlit' has no attribute 'title'

### ISSUE THREAD

**Issue by magnusviri** [jncraton/languagemodels#17]
Very cool project.

```
> python ./examples/streamlitchat.py
Traceback (most recent call last):
  File "/Users/jeng/ai/languagemodels/./examples/streamlitchat.py", line 8, in <module>
    import streamlit as st
  File "/Users/jeng/ai/languagemodels/examples/streamlit.py", line 11, in <module>
    st.title("[languagemodels](https://github.com/jncraton/languagemodels) Demo")
    ^^^^^^^^
AttributeError: partially initialized module 'streamlit' has no attribute 'title' (most likely due to a circular import)
```

I just learned what streamlit was and it looks like it is running on my computer, so it doesn't make sense that the script doesn't work.

```
> streamlit hello

      👋 Welcome to Streamlit!

      If you’d like to receive helpful onboarding emails, news, offers, promotions,
      and the occasional swag, please enter your email address below. Otherwise,
...
```

**Comment by magnusviri** [comment]
Nevermind! I played with streamlit more and can see I need to run it like this. Maybe the readme needs to make this clear.

```
streamlit run examples/streamlit.py
```
